name: Build and Publish PostgreSQL Docker Image

on:
  release:
    types:
    - created
    - edited

jobs:
  push-postgres-image:
    name: Push PostgreSQL Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ${{ secrets.DOCKER_REPO_POSTGRES }}:latest
          ${{ secrets.DOCKER_REPO_POSTGRES }}:${{ github.event.release.tag_name }}
